CREATE TABLE IF NOT EXISTS symptoms (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid(), 
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL,
    scale INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);