CREATE TABLE IF NOT EXISTS treatments (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    frecuency VARCHAR(255) NOT NULL,
    shots VARCHAR(255) NOT NULL,
    date_start TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_user FOREIGN KEY(user_id)
    REFERENCES users(id)
);