ALTER TABLE users ADD COLUMN date_of_birth DATE;
ALTER TABLE users ALTER COLUMN date_of_birth SET DEFAULT NULL;
ALTER TABLE users ALTER COLUMN date_of_birth DROP NOT NULL;
ALTER TABLE users DROP COLUMN age;
